version: '3.7'
services: 
  mongo5:
    container_name: mongo5-dev
    image: mongo:5.0
    env_file:
      - .env
    ports:
      - '60017:27017'
    volumes:
      - ./data:/data/db
  
  mongo-express: 
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo5
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '6082:8081'
    volumes:
      - ./data:/data/db